[Interface]
PrivateKey = oIrHFf4ZXtxVl1LmXVjJig3eOvgGLqoKTL9BPVT8H2c=
Address = 10.0.0.2/24
DNS = 8.8.8.8

[Peer]
PublicKey = 09CVQ8qJ2PratCSjQ71ko+dZ6gKL7HVw/aUkC4FgiHE=
Endpoint = 65.2.96.18:51820
AllowedIPs = 10.0.0.1/32
PersistentKeepalive = 25